name: images_to_pdf_example
description: Demonstrates how to use the images_to_pdf plugin.
publish_to: 'none'

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  path:
  path_provider:
  printing:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  images_to_pdf:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/01.png
    - assets/02.jpg
    - assets/03.jpg
    - assets/04.jpg
    - assets/05.jpg
    - assets/06.jpg
    - assets/07.jpg
    - assets/08.jpg
    - assets/09.jpg
    - assets/10.jpg
    - assets/11.jpg
    - assets/12.jpg
    - assets/13.jpg
